const productsObj = () => {
    return [
        {
            name:'Ovacado',
            amount_each: '1kg',
            id:1,
            amount:1,
            price:4,
            isFeatured:false,
            isInCart:false,
        },
        {
            name:'Cabbage',
            amount_each:'1 kg',
            id:2,
            amount:1,
            price:6,
            isFeatured:false,
            isInCart:false,
        },{
           name:'Colored capsicum',
           amount_each:'2kg',
           id:3,
           amount:1,
           price:5,
           isFeatured:false,
           isInCart:false,
        },
        {
            name:'Courgettes',
            amount_each:'2kg',
            id:4,
            amount:1,
            price:7,
            isFeatured:false,
            isInCart:false,
        },{
           name:'Colored capsicum',
           amount_each:'2kg',
           id:5,
           amount:1,
           price:5,
           isFeatured:false,
           isInCart:false,
        },
        {
            name:'Courgettes',
            amount_each:'2kg',
            id:6,
            amount:1,
            price:7,
            isFeatured:false,
            isInCart:false,
        },
        {
            name:'French beans',
            amount_each:'1kg',
            id:7,
            amount:1,
            price:7,
            isFeatured:false,
            isInCart:false,
        },
        {
            name:'Ovacado',
            amount_each: '1kg',
            id:8,
            amount:1,
            price:4,
            isFeatured:true,
            isInCart:false,
        },
        {
            name:'Cabbage',
            amount_each:'1 kg',
            id:9,
            amount:1,
            price:6,
            isFeatured:true,
            isInCart:false,
        },{
           name:'Colored capsicum',
           amount_each:'2kg',
           id:10,
           amount:1,
           price:5,
           isFeatured:true,
           isInCart:false,
        },
        {
            name:'Courgettes',
            amount_each:'2kg',
            id:11,
            amount:1,
            price:7,
            isFeatured:true,
            isInCart:false,
        },
        {
            name:'French beans',
            amount_each:'1kg',
            id:12,
            amount:1,
            price:7,
            isFeatured:false,
            isInCart:false,
        }
    ]
}

export default productsObj;
